# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
      
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: npm install hexo@3.9.0 hexo-deployer-git@0.2.0 hexo-generator-archive@0.1.4 hexo-generator-category@0.1.3 hexo-generator-index@0.2.0 hexo-generator-search@2.4.0 hexo-generator-tag@0.2.0 hexo-renderer-ejs@0.2.0 hexo-renderer-marked@0.2.11 hexo-renderer-stylus@0.3.1 hexo-server0.2.0

      # Runs a set of commands using the runners shell
      - name: Hexo Generate & Deploy
        run: |
          hexo generate,
          hexo deploy
